### PR TITLE
Fix delete model attributes beforeDelete

### PR DESCRIPTION
**Pull request by ArchimedeSolutions**
Added a bind event on beforeDelete to clean up attributes and indexes of the deleting model.

### CODE REVIEW

**Review by Teranode — COMMENTED** [review]
Consider changing the code to:

```php
        /*
         * Delete translated attributes/indexes if model is deleting
         */
        $this->model->bindEvent('model.beforeDelete', function() use ($model) {
            $model->translations()
                ->where('model_id', $model->getKey())
                ->where('model_type', get_class($model))
                ->delete();
```

`->translations()` having been a named method in https://github.com/wintercms/wn-translate-plugin/blob/d59a18bc21657b5d783052c4bd6faf885696f073/behaviors/TranslatableModel.php#L28

index can stay the same cause it's hardcoded.

**Comment by ArchimedeSolutions** [comment]
Hi Teranode!
Thanks for pointing this out.. last push has the correct code! The other changes come from an automated code formatting.

**Comment by ArchimedeSolutions** [comment]
Hi @Teranode ... any news about merging this?!

**Comment by LukeTowers** [comment]
@ArchimedeSolutions does this take into account soft deletion? Models that are softdeleted shouldn't have their translation data automatically removed until they are hard deleted. Are you able to test that out?

**Comment by Teranode** [comment]
> @ArchimedeSolutions does this take into account soft deletion? Models that are softdeleted shouldn't have their translation data automatically removed until they are hard deleted. Are you able to test that out?

so something like:
```php
/*
 * Delete translated attributes/indexes if model is deleting
 */
$model->bindEvent('model.afterDelete', function () use ($model) {
    if ( in_array(\Winter\Storm\Database\Traits\SoftDelete::class, class_uses(get_class($model))) && $model->trashed()) {
        return;
    }

    $model->translations()
        ->where('model_id', $model->getKey())
        ->where('model_type', get_class($model))
        ->delete();

    Db::table('winter_translate_indexes')
        ->where('model_id', $model->getKey())
        ->where('model_type', get_class($model))
        ->delete();
});
```

**Comment by mjauvin** [comment]
@ArchimedeSolutions are you still interested in merging this PR? If so, please can you look at integrating @Teranode's solution above for soft-deleted models and add some test cases?

**Comment by mjauvin** [comment]
Closing this as there's been no answer. Please reopen if you wish to complete this.

**Pull request closed without merging**
