### PR TITLE
Make sure tables don't exist before creating them in migrations

### PR DESCRIPTION
**Pull request by multiwebinc**
See #13

### CODE REVIEW

**Comment by LukeTowers** [comment]
This is a symptom of your RainLab plugin version being higher than the version that this plugin says that it can safely replace. @bennothommo @jaxwilko we should probably disable replacing plugins if they can't safely replace the replaced plugin so that these migrations won't be run in the first place if we aren't already doing that.

We should review the current version of RainLab.Translate and loosen our version targeting so that we don't have to update it all the time.

**Comment by multiwebinc** [comment]
@LukeTowers Fair enough. However, you might still want to take a look at the change to `updates/v1.3.1/add_sort_order.php` here, even if you don't merge the other changes.

**Comment by mjauvin** [comment]
@multiwebinc I'm closing this, can you create a new PR with only the fix for the sort_order migration ?

**Comment by multiwebinc** [comment]
@mjauvin Done. #23.

**Pull request closed without merging**
